image: java:8

variables:
  GRADLE_VERSION: "5.2.1"

# This build job does the full grails pipeline
# (compile, test, integrationTest, war, assemble).
build:
 script:
   - ./gradlew build

test:
  script:
    - ./gradlew test