image: java:8

variables:
  GRADLE_VERSION: "5.2.1"

before_script:
  # install zip and sdkman packages
   - apt-get update -qq && apt-get install -y -qq zip unzip
   - curl -sSL https://get.sdkman.io | bash
  # set auto answer property and add sdkman source
   - echo sdkman_auto_answer=true > /root/.sdkman/etc/config
   - source /root/.sdkman/bin/sdkman-init.sh
  # install gradle and grails with sdkman
   - sdk install gradle $GRADLE_VERSION < /dev/null
   - sdk use gradle $GRADLE_VERSION

# This build job does the full grails pipeline
# (compile, test, integrationTest, war, assemble).
build:
 script:
   - ./gradlew build

test:
  script:
    - ./gradlew test